[package]
name = "ela"
version = "0.1.0"
description = "high perference proxy"
authors = ["Kilerd Chan <blove694@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
actix-web = "1.0.2"
serde_derive = "1.0.93"
serde = "1.0.93"
toml = "0.5.1"
futures = "0.1.28"
url = "1.7.2"
