[package]
name = "ela"
version = "0.1.0"
description = "high perference proxy"
authors = ["Kilerd Chan <blove694@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
runtime = "0.3.0-alpha.5"
futures-preview = "0.3.0-alpha.16"